In [10]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("../yelp.db")

In [11]:
pd.read_sql(" SELECT COUNT(*) FROM business;", conn)

   COUNT(*)
0    150346

In [12]:
pd.read_sql("SELECT COUNT(*) FROM business WHERE categories IS NULL;", conn)

   COUNT(*)
0       103

In [13]:
pd.read_sql("SELECT COUNT(*) FROM business WHERE stars IS NULL OR review_count IS NULL;", conn)

   COUNT(*)
0         0

In [14]:
pd.read_sql("SELECT MIN(review_count), AVG(review_count), MAX(review_count) FROM business;", conn)

   MIN(review_count)  AVG(review_count)  MAX(review_count)
0                  5          44.866561               7568

In [15]:
pd.read_sql("""
SELECT
    -- on range chaque commerce dans une tranche selon son nombre d'avis
    CASE
        WHEN review_count < 10  THEN '1. 5-9 avis'
        WHEN review_count < 25  THEN '2. 10-24 avis'
        WHEN review_count < 100 THEN '3. 25-99 avis'
        WHEN review_count < 500 THEN '4. 100-499 avis'
        ELSE '5. 500+ avis'
    END AS tranche_avis,

    -- combien de commerces dans chaque tranche
    COUNT(*) AS nb_commerces,

    -- note moyenne des commerces de la tranche, arrondie à 2 décimales
    ROUND(AVG(stars), 2) AS note_moyenne

FROM business

-- on regroupe les commerces qui ont la même tranche
GROUP BY tranche_avis

-- on trie par nom de tranche (d'où les numéros 1., 2., 3.)
ORDER BY tranche_avis;
""", conn)

      tranche_avis  nb_commerces  note_moyenne
0      1. 5-9 avis         51103          3.61
1    2. 10-24 avis         46864          3.53
2    3. 25-99 avis         37732          3.58
3  4. 100-499 avis         13293          3.79
4     5. 500+ avis          1354          3.99